 /* tasks: 
     - name: aws cli install
       env: 
         AWS_CLI_AUTO_PROMPT: on-partial
       before: |
         cd /workspace
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install
         cd $THEIA_WORKSPACE_ROOT
         */
    tasks: 
     - name: aws cli install
       env: 
         AWS_CLI_AUTO_PROMPT: on-partial
       before: |
         cd D:\Aws\aws-solution-archite
            msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi
         cd $THEIA_WORKSPACE_ROOT
















